export const FETCH_MUSIC = 'FETCH_MUSIC';
export const FETCH_MUSIC_SUCCESS = 'FETCH_MUSIC_SUCCESS';
export const FETCH_MUSIC_FAILURE = 'FETCH_MUSIC_FAILURE';
export const PLAY_LIST_MUSIC = 'PLAY_LIST_MUSIC';
