export const ADD_MUSIC = 'ADD_MUSIC';
export const REMOVE_MUSIC = 'REMOVE_MUSIC';
export const PLAY_PLAYLIST_MUSIC = 'PLAY_PLAYLIST_MUSIC';
export const HIGHTLIGHT_PLAYING_MUSIC = "HIGHTLIGHT_PLAYING_MUSIC";