export const FETCH_COMPTABILITY = 'FETCH_COMPTABILITY';
export const FETCH_COMPTABILITY_SUCCESS = 'FETCH_COMPTABILITY_SUCCESS';
export const FETCH_COMPTABILITY_FAILURE = 'FETCH_COMPTABILITY_FAILURE';
export const PLAY_LIST_COMPTABILITY = 'PLAY_LIST_COMPTABILITY';
