export const ADD_MUSIC = 'ADD_MUSIC';
export const REMOVE_MUSIC = 'REMOVE_MUSIC';
export const CHANGE_PLAYING_MUSIC_ORDER = 'CHANGE_PLAYING_MUSIC_ORDER';
export const HIGHTLIGHT_PLAYING_MUSIC = "HIGHTLIGHT_PLAYING_MUSIC";